[project]
name = "delivery-intelligence-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "santhosh-madha", email = "madha.santhoshkr@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
delivery-intelligence-platform = "delivery_intelligence_platform:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
