"""create delivery outcomes table

Revision ID: 8bc4a9f5d424
Revises: 538cfc7454a1
Create Date: 2026-10-01 01:29:16.469850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc4a9f5d424'
down_revision: Union[str, Sequence[str], None] = '538cfc7454a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_outcomes',
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('actual_arrival_unix_s', sa.BigInteger(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_arrival_unix_s > 0 AND actual_arrival_unix_s < 9007199254740992', name='ck_delivery_outcomes_arrival'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_outcomes')
    # ### end Alembic commands ###
